export const SET_PLAYER_SELECTION = 'SET_PLAYER_SELECTION'
export const PLAYER_SUCCESSFULLY_DRAFTED = 'PLAYER_SUCCESSFULLY_DRAFTED'
export const DRAFT_PLAYER_REQUEST_SENT = 'DRAFT_PLAYDRAFT_PLAYER_REQUEST_SENTER_REQUEST'
export const SET_PLAYER_OWNER = 'SET_PLAYER_OWNER'