version: '3'

services:
  mysql-dev:
    image: mysql:latest
    container_name: mm_db
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: mm
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - "3306:3306"
  node-backend:
    build: backend
    container_name: mm_backend
    ports:
      - "8080:8080"
    environment:
      mm_mysql_host: mysql-dev
  node-frontend:
    build: frontend
    container_name: mm_frontend
    depends_on:
      - node-backend
    ports:
      - "8082:80"
    environment:
      PORT: 80
      VUE_APP_BACKEND_URL: "localhost:8080"
