version: '3'

services:
  node-backend:
    build: backend
    ports:
      - "8080:8080"
    environment:
      mm_mysql_host: "orion.cbtm6ac1xc5y.us-east-1.rds.amazonaws.com"
      mm_mysql_user: "mm_user"
      mm_mysql_pass: "GrapeJam321"
  node-frontend:
    build: frontend
    depends_on:
      - node-backend
    ports:
      - "80:80"
    environment:
      mm_backend_host: "34.239.114.7"
      mm_backend_port: 8080
      PORT: 80
