version: '3'

services:
  node-backend:
    build: backend
    container_name: mm_backend
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      mm_mysql_host: "orion.cbtm6ac1xc5y.us-east-1.rds.amazonaws.com"
      mm_mysql_user: "mm_user"
      mm_mysql_pass: "< change >"
  node-frontend:
    build: frontend
    container_name: mm_frontend
    restart: on-failure
    depends_on:
      - node-backend
    ports:
      - "80:80"
    environment:
      mm_backend_host: "mm.aleonard.us"
      mm_backend_port: 8080
      PORT: 80
      backend_url: mm.aleonard.us:8080
