version: '3'

services:
  mysql-dev:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: mm
    ports:
      - "3306:3306"
    volumes:
      - "./database/data:/var/lib/mysql:rw"
  # node-backend:
  #   image: adamback
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     mm_mysql_host: mysql-dev
