version: '3'

services:
  mysql-dev:
    image: mysql:8.0.4
    container_name: mm_db
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: mm
    ports:
      - "3306:3306"
  node-backend:
    build: backend
    container_name: mm_backend
    ports:
      - "8080:8080"
    environment:
      mm_mysql_host: mysql-dev
  node-frontend:
    build: frontend
    container_name: mm_frontend
    depends_on:
      - node-backend
    ports:
      - "8082:80"
    environment:
      mm_backend_host: "localhost"
      mm_backend_port: 8080
      PORT: 80
