version: '3'

services:
  node-backend:
    build: backend
    container_name: mm_backend
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      mm_mysql_host: "< change >" # TODO: Change this
      mm_mysql_user: "mm_user"
      mm_mysql_pass: "< change >" # TODO: Change this
  node-frontend:
    build: frontend-prod
    container_name: mm_frontend
    restart: on-failure
    depends_on:
      - node-backend
    ports:
      - "80:80"
    environment:
      VUE_APP_BACKEND_URL: "http://mm.aleonard.us:8080"
